[[snippets]]
id = "1"
title = "Snippetti"
address = "/Users/pavel/dev/experiments/snippetti"
description = "The semantic bookmark search app"
tags = [
    "code",
    "python",
    "experiments",
]

[[snippets]]
id = "2"
title = "Mein Architekturportfolio - Layouts"
address = "/Users/pavel/Documents/Portfolio"
description = "Mein Architekturportfolio mit alle Indesign und Affinity Layouts und Bibliotheken"
tags = []
